{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "title: \"Webscraping Indeed Job Portal\"\n",
    "description: \"webscraping with python and using proxies\"\n",
    "author: \"Aakash Basnet\"\n",
    "date: \"2024/02/03\"\n",
    "categories:\n",
    "  - webscraping\n",
    "  - code\n",
    "  - ETL\n",
    "  - python\n",
    "format:\n",
    "  html:\n",
    "    code-fold: true\n",
    "jupyter: python3\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##  Building URL\n",
    "After navigating the developer toolbar for Indeed job listing, I found the pattern in the url query for each job title search and location. We can use this info to build the url. The link printed from the code below will take you to the Indeed page having listing for python developer in Dalla, TX"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://www.indeed.com/jobs?q=python+developer&l=Dallas,+TX\n"
     ]
    }
   ],
   "source": [
    "def url_builder(job_title, location, page_number=10 ):\n",
    "    job_title = \"+\".join(job_title.split(\" \"))\n",
    "    location = \"+\".join(location.split(\" \"))\n",
    "    base_url = \"https://www.indeed.com/jobs\"\n",
    "    query_str = f\"?q={job_title}&l={location}\"\n",
    "    url = f\"{base_url}{query_str}\"\n",
    "     \n",
    "    return url\n",
    "\n",
    "print(url_builder(job_title=\"python developer\", location=\"Dallas, TX\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Rotating Proxies\n",
    "The proxies needs to be rotated to not be detected by anti scrapping tools used by the servers. For this we will scrape the list of free available ip address and test them using multithreading. This will filter the working proxies. Later on, we will use working proxies to make the request"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "\n",
    "\n",
    "def extract_proxies():\n",
    "    print(\"Extracting proxies...\")\n",
    "    proxy_url  = \"https://free-proxy-list.net/\"\n",
    "    r = requests.get(proxy_url)\n",
    "    dfs  = pd.read_html(r.text)\n",
    "    df = dfs[0]\n",
    "    print(df.shape)\n",
    "    return df\n",
    "\n",
    "   \n",
    "def test_proxy(proxy):\n",
    "    url= \"https://www.google.com\"\n",
    "    print(f\"testing {proxy}\")\n",
    "    try:\n",
    "        r = requests.get(url, proxies={\"http\": proxy , \"https\": proxy}, timeout=5)\n",
    "    except Exception as e:\n",
    "        print(e)\n",
    "        return None\n",
    "        \n",
    "    print(r.status_code)\n",
    "    if r.status_code == 200: \n",
    "        return proxy\n",
    "    return None   \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting proxies...\n",
      "(300, 8)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/22/2rvpv_m90c30mhtk77k1jd440000gn/T/ipykernel_43959/1286072462.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.\n",
      "  dfs  = pd.read_html(r.text)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>IP Address</th>\n",
       "      <th>Port</th>\n",
       "      <th>Code</th>\n",
       "      <th>Country</th>\n",
       "      <th>Anonymity</th>\n",
       "      <th>Google</th>\n",
       "      <th>Https</th>\n",
       "      <th>Last Checked</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>140.238.18.180</td>\n",
       "      <td>21000</td>\n",
       "      <td>KR</td>\n",
       "      <td>South Korea</td>\n",
       "      <td>elite proxy</td>\n",
       "      <td>NaN</td>\n",
       "      <td>yes</td>\n",
       "      <td>0 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>114.129.2.82</td>\n",
       "      <td>8081</td>\n",
       "      <td>JP</td>\n",
       "      <td>Japan</td>\n",
       "      <td>elite proxy</td>\n",
       "      <td>no</td>\n",
       "      <td>yes</td>\n",
       "      <td>0 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>113.161.131.43</td>\n",
       "      <td>80</td>\n",
       "      <td>VN</td>\n",
       "      <td>Vietnam</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>116.203.28.43</td>\n",
       "      <td>80</td>\n",
       "      <td>DE</td>\n",
       "      <td>Germany</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>209.121.164.50</td>\n",
       "      <td>31147</td>\n",
       "      <td>CA</td>\n",
       "      <td>Canada</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>NaN</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>198.44.255.3</td>\n",
       "      <td>80</td>\n",
       "      <td>HK</td>\n",
       "      <td>Hong Kong</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>139.162.78.109</td>\n",
       "      <td>3128</td>\n",
       "      <td>JP</td>\n",
       "      <td>Japan</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>89.36.114.38</td>\n",
       "      <td>80</td>\n",
       "      <td>GB</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>41.207.187.178</td>\n",
       "      <td>80</td>\n",
       "      <td>TG</td>\n",
       "      <td>Togo</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>198.176.56.43</td>\n",
       "      <td>80</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>154.118.228.212</td>\n",
       "      <td>80</td>\n",
       "      <td>TZ</td>\n",
       "      <td>Tanzania</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>195.181.172.230</td>\n",
       "      <td>8082</td>\n",
       "      <td>NL</td>\n",
       "      <td>Netherlands</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>45.5.2.246</td>\n",
       "      <td>8084</td>\n",
       "      <td>AR</td>\n",
       "      <td>Argentina</td>\n",
       "      <td>elite proxy</td>\n",
       "      <td>NaN</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>50.237.207.186</td>\n",
       "      <td>80</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>32.223.6.94</td>\n",
       "      <td>80</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>8 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>67.43.228.250</td>\n",
       "      <td>18003</td>\n",
       "      <td>CA</td>\n",
       "      <td>Canada</td>\n",
       "      <td>elite proxy</td>\n",
       "      <td>yes</td>\n",
       "      <td>yes</td>\n",
       "      <td>24 secs ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>103.127.1.130</td>\n",
       "      <td>80</td>\n",
       "      <td>BD</td>\n",
       "      <td>Bangladesh</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>NaN</td>\n",
       "      <td>no</td>\n",
       "      <td>1 min ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>51.15.242.202</td>\n",
       "      <td>8888</td>\n",
       "      <td>FR</td>\n",
       "      <td>France</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>1 min ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>47.56.110.204</td>\n",
       "      <td>8989</td>\n",
       "      <td>HK</td>\n",
       "      <td>Hong Kong</td>\n",
       "      <td>anonymous</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>1 min ago</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>34.135.166.24</td>\n",
       "      <td>80</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>elite proxy</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>1 min ago</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         IP Address   Port Code         Country    Anonymity Google Https  \\\n",
       "0    140.238.18.180  21000   KR     South Korea  elite proxy    NaN   yes   \n",
       "1      114.129.2.82   8081   JP           Japan  elite proxy     no   yes   \n",
       "2    113.161.131.43     80   VN         Vietnam    anonymous     no    no   \n",
       "3     116.203.28.43     80   DE         Germany    anonymous    yes    no   \n",
       "4    209.121.164.50  31147   CA          Canada    anonymous    NaN    no   \n",
       "5      198.44.255.3     80   HK       Hong Kong    anonymous     no    no   \n",
       "6    139.162.78.109   3128   JP           Japan    anonymous     no    no   \n",
       "7      89.36.114.38     80   GB  United Kingdom    anonymous    yes    no   \n",
       "8    41.207.187.178     80   TG            Togo    anonymous     no    no   \n",
       "9     198.176.56.43     80   US   United States    anonymous    yes    no   \n",
       "10  154.118.228.212     80   TZ        Tanzania    anonymous     no    no   \n",
       "11  195.181.172.230   8082   NL     Netherlands    anonymous     no    no   \n",
       "12       45.5.2.246   8084   AR       Argentina  elite proxy    NaN    no   \n",
       "13   50.237.207.186     80   US   United States    anonymous     no    no   \n",
       "14      32.223.6.94     80   US   United States    anonymous     no    no   \n",
       "15    67.43.228.250  18003   CA          Canada  elite proxy    yes   yes   \n",
       "16    103.127.1.130     80   BD      Bangladesh    anonymous    NaN    no   \n",
       "17    51.15.242.202   8888   FR          France    anonymous     no    no   \n",
       "18    47.56.110.204   8989   HK       Hong Kong    anonymous    yes    no   \n",
       "19    34.135.166.24     80   US   United States  elite proxy    yes    no   \n",
       "\n",
       "   Last Checked  \n",
       "0    0 secs ago  \n",
       "1    0 secs ago  \n",
       "2    8 secs ago  \n",
       "3    8 secs ago  \n",
       "4    8 secs ago  \n",
       "5    8 secs ago  \n",
       "6    8 secs ago  \n",
       "7    8 secs ago  \n",
       "8    8 secs ago  \n",
       "9    8 secs ago  \n",
       "10   8 secs ago  \n",
       "11   8 secs ago  \n",
       "12   8 secs ago  \n",
       "13   8 secs ago  \n",
       "14   8 secs ago  \n",
       "15  24 secs ago  \n",
       "16    1 min ago  \n",
       "17    1 min ago  \n",
       "18    1 min ago  \n",
       "19    1 min ago  "
      ]
     },
     "execution_count": 71,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "proxies_df = extract_proxies()\n",
    "proxies_df.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting proxies...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/22/2rvpv_m90c30mhtk77k1jd440000gn/T/ipykernel_43959/2333997394.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.\n",
      "  dfs  = pd.read_html(r.text)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(300, 8)\n",
      "testing 140.238.18.180\n",
      "testing 114.129.2.82\n",
      "testing 113.161.131.43\n",
      "testing 116.203.28.43\n",
      "testing 209.121.164.50\n",
      "testing 198.44.255.3\n",
      "testing 139.162.78.109\n",
      "testing 89.36.114.38\n",
      "testing 41.207.187.178\n",
      "testing 198.176.56.43\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133820ee0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 154.118.228.212\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133821ff0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 195.181.172.230\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable')))\n",
      "testing 45.5.2.246\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable')))\n",
      "testing 50.237.207.186\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 32.223.6.94\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 67.43.228.250\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "testing 103.127.1.130\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133a65840>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 51.15.242.202\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 47.56.110.204\n",
      "('Connection aborted.', BadStatusLine('SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.7\\r\\n'))\n",
      "testing 34.135.166.24\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "testing 103.163.51.254\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 47.243.177.210\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 54.207.116.122\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 109.70.189.30\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 50.173.140.146\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133a66350>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 50.172.75.120\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 50.172.75.123\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "testing 50.206.111.90\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))\n",
      "testing 50.122.86.118\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1304ff310>, 'Connection to 114.129.2.82 timed out. (connect timeout=5)')))HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820940>, 'Connection to 41.207.187.178 timed out. (connect timeout=5)')))\n",
      "testing 213.157.6.50\n",
      "\n",
      "testing 85.26.146.169\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1332305e0>, 'Connection to 50.237.207.186 timed out. (connect timeout=5)')))\n",
      "testing 50.218.57.70\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6ec0>, 'Connection to 32.223.6.94 timed out. (connect timeout=5)')))\n",
      "testing 54.248.238.110\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65000>, 'Connection to 54.207.116.122 timed out. (connect timeout=5)')))\n",
      "testing 50.223.38.6\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 50.168.163.179\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6320>, 'Connection to 50.173.140.146 timed out. (connect timeout=5)')))\n",
      "testing 50.221.230.186\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821480>, 'Connection to 50.172.75.120 timed out. (connect timeout=5)')))\n",
      "testing 50.172.23.10\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820490>, 'Connection to 50.172.75.123 timed out. (connect timeout=5)')))\n",
      "testing 50.222.245.42\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64340>, 'Connection to 50.206.111.90 timed out. (connect timeout=5)')))\n",
      "testing 50.173.140.151\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65cf0>, 'Connection to 50.122.86.118 timed out. (connect timeout=5)')))\n",
      "testing 50.239.72.18\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5900>, 'Connection to 213.157.6.50 timed out. (connect timeout=5)')))HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5990>, 'Connection to 85.26.146.169 timed out. (connect timeout=5)')))\n",
      "testing 3.37.125.76\n",
      "\n",
      "testing 213.143.113.82\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133337250>, 'Connection to 50.218.57.70 timed out. (connect timeout=5)')))\n",
      "testing 50.173.140.150\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 50.221.74.130\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6b00>, 'Connection to 50.223.38.6 timed out. (connect timeout=5)')))\n",
      "testing 50.175.212.66\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64550>, 'Connection to 50.168.163.179 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.157\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a65c0>, 'Connection to 50.221.230.186 timed out. (connect timeout=5)')))\n",
      "testing 50.217.226.40\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a649d0>, 'Connection to 50.222.245.42 timed out. (connect timeout=5)')))\n",
      "testing 50.174.145.9\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64640>, 'Connection to 50.172.23.10 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.162\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65ba0>, 'Connection to 50.173.140.151 timed out. (connect timeout=5)')))\n",
      "testing 47.243.205.1\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "testing 50.218.57.66\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a654e0>, 'Connection to 50.239.72.18 timed out. (connect timeout=5)')))\n",
      "testing 50.174.145.12\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a48b0>, 'Connection to 213.143.113.82 timed out. (connect timeout=5)')))\n",
      "testing 50.168.163.183\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338207f0>, 'Connection to 50.173.140.150 timed out. (connect timeout=5)')))\n",
      "testing 54.233.119.172\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a654b0>, 'Connection to 50.221.74.130 timed out. (connect timeout=5)')))\n",
      "testing 13.38.176.104\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 50.204.219.229\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65f90>, 'Connection to 50.175.212.66 timed out. (connect timeout=5)')))\n",
      "testing 50.222.245.41\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd420>, 'Connection to 50.174.7.157 timed out. (connect timeout=5)')))\n",
      "testing 50.206.111.88\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 50.175.212.74\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7f10>, 'Connection to 50.217.226.40 timed out. (connect timeout=5)')))\n",
      "testing 0.0.0.0\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338206d0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 50.174.7.152\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64220>, 'Connection to 50.174.145.9 timed out. (connect timeout=5)')))HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65cf0>, 'Connection to 50.174.7.162 timed out. (connect timeout=5)')))\n",
      "testing 50.239.72.19\n",
      "\n",
      "testing 50.235.240.86\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a67250>, 'Connection to 50.218.57.66 timed out. (connect timeout=5)')))\n",
      "testing 50.174.145.8\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7f70>, 'Connection to 50.174.145.12 timed out. (connect timeout=5)')))\n",
      "testing 82.119.96.254\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7d30>, 'Connection to 50.168.163.183 timed out. (connect timeout=5)')))\n",
      "testing 50.218.57.71\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65090>, 'Connection to 50.204.219.229 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.159\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6890>, 'Connection to 50.222.245.41 timed out. (connect timeout=5)')))\n",
      "testing 50.172.75.121\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7280>, 'Connection to 50.206.111.88 timed out. (connect timeout=5)')))\n",
      "testing 50.207.199.84\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822410>, 'Connection to 50.175.212.74 timed out. (connect timeout=5)')))\n",
      "testing 50.206.111.91\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65ff0>, 'Connection to 50.174.7.152 timed out. (connect timeout=5)')))\n",
      "testing 50.172.75.126\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821750>, 'Connection to 50.239.72.19 timed out. (connect timeout=5)')))HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821030>, 'Connection to 50.235.240.86 timed out. (connect timeout=5)')))\n",
      "testing 72.10.160.91\n",
      "\n",
      "testing 50.207.199.80\n",
      "('Connection aborted.', BadStatusLine('SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.8\\r\\n'))\n",
      "testing 50.239.72.16\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdbbd60>, 'Connection to 50.174.145.8 timed out. (connect timeout=5)')))\n",
      "testing 50.217.226.43\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a68c0>, 'Connection to 82.119.96.254 timed out. (connect timeout=5)')))\n",
      "testing 50.172.75.124\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd3c0>, 'Connection to 50.218.57.71 timed out. (connect timeout=5)')))\n",
      "testing 50.170.90.25\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a66b30>, 'Connection to 50.174.7.159 timed out. (connect timeout=5)')))\n",
      "testing 50.231.172.74\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1335b91e0>, 'Connection to 50.172.75.121 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.158\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5060>, 'Connection to 50.207.199.84 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.153\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dcfa0>, 'Connection to 50.206.111.91 timed out. (connect timeout=5)')))\n",
      "testing 50.169.135.10\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64af0>, 'Connection to 50.172.75.126 timed out. (connect timeout=5)')))\n",
      "testing 50.207.199.82\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339ddb10>, 'Connection to 50.207.199.80 timed out. (connect timeout=5)')))\n",
      "testing 50.207.199.81\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822290>, 'Connection to 50.239.72.16 timed out. (connect timeout=5)')))\n",
      "testing 50.174.7.155\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338204f0>, 'Connection to 50.217.226.43 timed out. (connect timeout=5)')))\n",
      "testing 50.175.212.72\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1337623b0>, 'Connection to 50.172.75.124 timed out. (connect timeout=5)')))\n",
      "testing 47.74.152.29\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a7d30>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 66.191.31.158\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7b80>, 'Connection to 50.170.90.25 timed out. (connect timeout=5)')))\n",
      "testing 50.173.140.144\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4310>, 'Connection to 50.231.172.74 timed out. (connect timeout=5)')))\n",
      "testing 50.231.110.26\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd300>, 'Connection to 50.174.7.158 timed out. (connect timeout=5)')))\n",
      "testing 50.168.210.232\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6710>, 'Connection to 50.174.7.153 timed out. (connect timeout=5)')))\n",
      "testing 50.204.219.227\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4850>, 'Connection to 50.169.135.10 timed out. (connect timeout=5)')))\n",
      "testing 190.58.248.86\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1304fca90>, 'Connection to 50.207.199.82 timed out. (connect timeout=5)')))\n",
      "testing 50.168.72.113\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a65c00>, 'Connection to 50.207.199.81 timed out. (connect timeout=5)')))\n",
      "testing 50.173.140.149\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5d50>, 'Connection to 50.174.7.155 timed out. (connect timeout=5)')))\n",
      "testing 50.207.199.87\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dfca0>, 'Connection to 50.175.212.72 timed out. (connect timeout=5)')))\n",
      "testing 50.218.57.69\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5000>, 'Connection to 66.191.31.158 timed out. (connect timeout=5)')))\n",
      "testing 80.150.50.226\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a67100>, 'Connection to 50.173.140.144 timed out. (connect timeout=5)')))\n",
      "testing 50.222.245.43\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdf0100>, 'Connection to 50.231.110.26 timed out. (connect timeout=5)')))\n",
      "testing 50.174.145.13\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7880>, 'Connection to 50.168.210.232 timed out. (connect timeout=5)')))\n",
      "testing 50.200.12.83\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd150>, 'Connection to 50.204.219.227 timed out. (connect timeout=5)')))\n",
      "testing 50.222.245.46\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133763e80>, 'Connection to 190.58.248.86 timed out. (connect timeout=5)')))\n",
      "testing 158.101.113.18\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822c50>, 'Connection to 50.168.72.113 timed out. (connect timeout=5)')))\n",
      "testing 176.235.182.99\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820070>, 'Connection to 50.173.140.149 timed out. (connect timeout=5)')))\n",
      "testing 72.169.67.17\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133903940>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 71.42.125.219\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e4c3a0>, 'Connection to 50.207.199.87 timed out. (connect timeout=5)')))\n",
      "testing 118.172.187.127\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 217.88.74.135\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133821720>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 41.57.46.1\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133822110>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 103.169.130.17\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a7df0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 154.38.174.24\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1331a4ac0>, 'Connection to 50.218.57.69 timed out. (connect timeout=5)')))\n",
      "testing 45.71.15.136\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339def80>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 190.61.101.39\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a7c70>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 141.148.63.29\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902e30>, 'Connection to 80.150.50.226 timed out. (connect timeout=5)')))\n",
      "testing 13.37.59.99\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 3.122.84.99\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a61d0>, 'Connection to 50.222.245.43 timed out. (connect timeout=5)')))\n",
      "testing 50.223.246.226\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 50.200.12.81\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6680>, 'Connection to 50.174.145.13 timed out. (connect timeout=5)')))\n",
      "testing 50.219.244.0\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a59c0>, 'Connection to 50.200.12.83 timed out. (connect timeout=5)')))\n",
      "testing 72.10.160.171\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7a30>, 'Connection to 50.222.245.46 timed out. (connect timeout=5)')))\n",
      "testing 172.245.110.29\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5bd0>, 'Connection to 158.101.113.18 timed out. (connect timeout=5)')))\n",
      "testing 50.200.12.85\n",
      "('Connection aborted.', BadStatusLine('SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.8\\r\\n'))\n",
      "testing 15.236.106.236\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a64b20>, 'Connection to 72.169.67.17 timed out. (connect timeout=5)')))\n",
      "testing 50.217.226.47\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 50.168.72.115\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))\n",
      "testing 84.39.112.144\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339034c0>, 'Connection to 41.57.46.1 timed out. (connect timeout=5)')))\n",
      "testing 50.170.90.26\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a6620>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 133.18.234.13\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1304fec50>, 'Connection to 45.71.15.136 timed out. (connect timeout=5)')))\n",
      "testing 50.168.72.117\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822200>, 'Connection to 141.148.63.29 timed out. (connect timeout=5)')))\n",
      "testing 50.169.118.211\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable')))\n",
      "testing 50.239.72.17\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900fd0>, 'Connection to 50.223.246.226 timed out. (connect timeout=5)')))\n",
      "testing 50.218.57.68\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7d90>, 'Connection to 50.200.12.81 timed out. (connect timeout=5)')))\n",
      "testing 213.33.2.28\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4d30>, 'Connection to 50.219.244.0 timed out. (connect timeout=5)')))\n",
      "testing 50.217.226.46\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339df520>, 'Connection to 50.200.12.85 timed out. (connect timeout=5)')))\n",
      "testing 50.218.57.64\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5a20>, 'Connection to 50.217.226.47 timed out. (connect timeout=5)')))\n",
      "testing 50.168.7.250\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4a00>, 'Connection to 50.168.72.115 timed out. (connect timeout=5)')))\n",
      "testing 50.172.227.202\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820910>, 'Connection to 50.170.90.26 timed out. (connect timeout=5)')))\n",
      "testing 139.59.1.14\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133a66fb0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 50.175.212.79\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4c40>, 'Connection to 50.168.72.117 timed out. (connect timeout=5)')))\n",
      "testing 91.185.58.230\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339de8c0>, 'Connection to 50.169.118.211 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.116\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338211e0>, 'Connection to 50.239.72.17 timed out. (connect timeout=5)')))\n",
      "testing 209.127.39.127\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339023b0>, 'Connection to 50.218.57.68 timed out. (connect timeout=5)')))\n",
      "testing 154.83.9.30\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339010c0>, 'Connection to 213.33.2.28 timed out. (connect timeout=5)')))\n",
      "testing 154.202.97.20\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fcd0>, 'Connection to 50.217.226.46 timed out. (connect timeout=5)')))\n",
      "testing 154.202.106.114\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822410>, 'Connection to 50.218.57.64 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.34\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6710>, 'Connection to 50.168.7.250 timed out. (connect timeout=5)')))\n",
      "testing 154.202.112.42\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339032b0>, 'Connection to 50.172.227.202 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.235\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901f30>, 'Connection to 50.175.212.79 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.160\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e4dff0>, 'Connection to 91.185.58.230 timed out. (connect timeout=5)')))\n",
      "testing 203.79.29.150\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd510>, 'Connection to 38.15.154.116 timed out. (connect timeout=5)')))\n",
      "testing 159.89.175.22\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4e80>, 'Connection to 209.127.39.127 timed out. (connect timeout=5)')))\n",
      "testing 118.97.164.19\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133820910>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 179.60.235.248\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339df6a0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 103.167.15.213\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 unknown method')))HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 31.207.34.116\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a6500>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 196.251.221.30\n",
      "\n",
      "testing 125.229.149.168\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339dddb0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 1.0.171.213\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133822290>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 154.202.106.191\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338207c0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 154.202.106.249\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 unknown method')))\n",
      "testing 38.15.152.24\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a71f0>, 'Connection to 154.83.9.30 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.216\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdc9660>, 'Connection to 154.202.97.20 timed out. (connect timeout=5)')))\n",
      "testing 154.202.126.153\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820700>, 'Connection to 154.202.106.114 timed out. (connect timeout=5)')))\n",
      "testing 209.127.39.100\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dc0d0>, 'Connection to 38.15.152.34 timed out. (connect timeout=5)')))\n",
      "testing 154.202.119.95\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339037c0>, 'Connection to 154.202.112.42 timed out. (connect timeout=5)')))\n",
      "testing 209.127.76.201\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902290>, 'Connection to 38.15.155.235 timed out. (connect timeout=5)')))\n",
      "testing 104.165.127.19\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6f50>, 'Connection to 38.15.152.160 timed out. (connect timeout=5)')))\n",
      "testing 154.202.108.23\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5b10>, 'Connection to 154.202.106.191 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.35\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6fb0>, 'Connection to 154.202.106.249 timed out. (connect timeout=5)')))\n",
      "testing 154.202.125.2\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339df190>, 'Connection to 38.15.152.24 timed out. (connect timeout=5)')))\n",
      "testing 154.202.109.204\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338233a0>, 'Connection to 172.245.166.216 timed out. (connect timeout=5)')))\n",
      "testing 65.21.131.54\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339020e0>, 'Connection to 154.202.126.153 timed out. (connect timeout=5)')))\n",
      "testing 154.201.61.205\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))\n",
      "testing 209.127.76.34\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fdf0>, 'Connection to 209.127.39.100 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.20\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133a66710>, 'Connection to 154.202.119.95 timed out. (connect timeout=5)')))\n",
      "testing 154.83.8.147\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dcf70>, 'Connection to 209.127.76.201 timed out. (connect timeout=5)')))\n",
      "testing 154.202.118.28\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133903eb0>, 'Connection to 104.165.127.19 timed out. (connect timeout=5)')))\n",
      "testing 209.127.76.92\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820eb0>, 'Connection to 154.202.108.23 timed out. (connect timeout=5)')))\n",
      "testing 154.202.120.153\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4820>, 'Connection to 172.245.166.35 timed out. (connect timeout=5)')))\n",
      "testing 186.121.214.210\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5cf0>, 'Connection to 154.202.125.2 timed out. (connect timeout=5)')))\n",
      "testing 154.202.126.179\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339ddd20>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 172.245.166.225\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdf3820>, 'Connection to 154.202.109.204 timed out. (connect timeout=5)')))\n",
      "testing 43.243.172.2\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339dd120>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 38.15.155.205\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5c60>, 'Connection to 154.201.61.205 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.121\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5b10>, 'Connection to 209.127.76.34 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.149\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339016c0>, 'Connection to 38.15.152.20 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.149\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900c40>, 'Connection to 154.83.8.147 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.173\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e66800>, 'Connection to 154.202.118.28 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.115\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fdc0>, 'Connection to 209.127.76.92 timed out. (connect timeout=5)')))\n",
      "testing 154.202.108.73\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5840>, 'Connection to 154.202.120.153 timed out. (connect timeout=5)')))\n",
      "testing 103.155.54.233\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1338a7d90>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 41.65.0.204\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820550>, 'Connection to 154.202.126.179 timed out. (connect timeout=5)')))\n",
      "testing 154.202.109.138\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f11b0>, 'Connection to 172.245.166.225 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.97\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339025c0>, 'Connection to 38.15.155.205 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.251\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820970>, 'Connection to 38.15.153.121 timed out. (connect timeout=5)')))\n",
      "testing 154.202.109.198\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133822230>, 'Connection to 172.245.166.149 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.158\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6a10>, 'Connection to 38.15.152.149 timed out. (connect timeout=5)')))\n",
      "testing 154.202.106.20\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339005b0>, 'Connection to 38.15.152.173 timed out. (connect timeout=5)')))\n",
      "testing 154.202.124.111\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f1b40>, 'Connection to 192.210.159.115 timed out. (connect timeout=5)')))\n",
      "testing 209.127.31.236\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6b90>, 'Connection to 154.202.108.73 timed out. (connect timeout=5)')))\n",
      "testing 24.230.33.96\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 404 Not Found')))\n",
      "testing 38.15.155.215\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7bb0>, 'Connection to 41.65.0.204 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.133\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dc9a0>, 'Connection to 154.202.109.138 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.151\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901c60>, 'Connection to 38.15.153.97 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.101\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1331a4d90>, 'Connection to 172.245.166.251 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.110\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f1750>, 'Connection to 154.202.109.198 timed out. (connect timeout=5)')))\n",
      "testing 209.127.39.109\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a6f50>, 'Connection to 192.210.159.158 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.152\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a5630>, 'Connection to 154.202.106.20 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.232\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133903dc0>, 'Connection to 154.202.124.111 timed out. (connect timeout=5)')))\n",
      "testing 154.201.61.139\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338233a0>, 'Connection to 209.127.31.236 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.174\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f0670>, 'Connection to 38.15.155.215 timed out. (connect timeout=5)')))\n",
      "testing 209.127.76.163\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a7fd0>, 'Connection to 192.210.159.133 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.6\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821450>, 'Connection to 38.15.154.151 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.157\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f3a90>, 'Connection to 192.210.159.101 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.118\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f3c40>, 'Connection to 38.15.153.110 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.128\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133903c40>, 'Connection to 209.127.39.109 timed out. (connect timeout=5)')))\n",
      "testing 209.127.31.232\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900130>, 'Connection to 192.210.159.152 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.212\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1304fec50>, 'Connection to 38.15.155.232 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.253\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e4dff0>, 'Connection to 154.201.61.139 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.187\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338209d0>, 'Connection to 172.245.166.174 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.221\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133903250>, 'Connection to 209.127.76.163 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.21\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd660>, 'Connection to 38.15.154.6 timed out. (connect timeout=5)')))\n",
      "testing 154.202.122.85\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dcd00>, 'Connection to 192.210.159.157 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.47\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dda80>, 'Connection to 38.15.155.118 timed out. (connect timeout=5)')))\n",
      "testing 154.201.63.9\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821960>, 'Connection to 38.15.154.128 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.149\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338224d0>, 'Connection to 209.127.31.232 timed out. (connect timeout=5)')))\n",
      "testing 154.84.140.180\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f0a30>, 'Connection to 38.15.154.212 timed out. (connect timeout=5)')))\n",
      "testing 154.83.9.154\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339039a0>, 'Connection to 38.15.155.253 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.193\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1332305e0>, 'Connection to 172.245.166.187 timed out. (connect timeout=5)')))\n",
      "testing 154.84.142.145\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fdf0>, 'Connection to 38.15.153.221 timed out. (connect timeout=5)')))\n",
      "testing 154.202.108.63\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902950>, 'Connection to 192.210.159.21 timed out. (connect timeout=5)')))\n",
      "testing 154.83.8.103\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902b30>, 'Connection to 154.202.122.85 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.188\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f08e0>, 'Connection to 172.245.166.47 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.133\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338a4d00>, 'Connection to 154.201.63.9 timed out. (connect timeout=5)')))\n",
      "testing 154.202.121.176\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5c90>, 'Connection to 38.15.153.149 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.214\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339ddd20>, 'Connection to 154.84.140.180 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.93\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339020e0>, 'Connection to 154.83.9.154 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.136\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f2f50>, 'Connection to 38.15.155.193 timed out. (connect timeout=5)')))\n",
      "testing 209.127.31.162\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338206a0>, 'Connection to 154.84.142.145 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.125\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fee0>, 'Connection to 154.202.108.63 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.111\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901e40>, 'Connection to 154.83.8.103 timed out. (connect timeout=5)')))\n",
      "testing 154.202.113.5\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e67ee0>, 'Connection to 38.15.155.188 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.72\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f33a0>, 'Connection to 38.15.155.133 timed out. (connect timeout=5)')))\n",
      "testing 154.84.143.223\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820940>, 'Connection to 154.202.121.176 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.0\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130f710f0>, 'Connection to 38.15.152.214 timed out. (connect timeout=5)')))\n",
      "testing 209.127.76.95\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f2830>, 'Connection to 38.15.154.93 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.112\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f38b0>, 'Connection to 38.15.155.136 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.13\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902260>, 'Connection to 209.127.31.162 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.170\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339039d0>, 'Connection to 38.15.155.125 timed out. (connect timeout=5)')))\n",
      "testing 154.202.119.107\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821150>, 'Connection to 172.245.166.111 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.29\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdf0dc0>, 'Connection to 154.202.113.5 timed out. (connect timeout=5)')))\n",
      "testing 154.202.97.118\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1332306d0>, 'Connection to 192.210.159.72 timed out. (connect timeout=5)')))\n",
      "testing 154.84.143.51\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f29b0>, 'Connection to 154.84.143.223 timed out. (connect timeout=5)')))\n",
      "testing 154.83.11.64\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900040>, 'Connection to 192.210.159.0 timed out. (connect timeout=5)')))\n",
      "testing 161.49.215.28\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x133901930>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 154.202.117.165\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339de8c0>, 'Connection to 209.127.76.95 timed out. (connect timeout=5)')))\n",
      "testing 154.202.121.76\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1337623b0>, 'Connection to 38.15.152.112 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.172\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339df550>, 'Connection to 38.15.155.13 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.144\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f11e0>, 'Connection to 38.15.154.170 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.60\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900bb0>, 'Connection to 154.202.119.107 timed out. (connect timeout=5)')))\n",
      "testing 154.201.63.125\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133821180>, 'Connection to 38.15.152.29 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.14\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338233a0>, 'Connection to 154.202.97.118 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.107\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdc9660>, 'Connection to 154.84.143.51 timed out. (connect timeout=5)')))\n",
      "testing 154.84.142.117\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1332312a0>, 'Connection to 154.83.11.64 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.133\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900b50>, 'Connection to 154.202.117.165 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.238\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f1c90>, 'Connection to 154.202.121.76 timed out. (connect timeout=5)')))\n",
      "testing 185.105.230.45\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339dd060>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 192.210.159.235\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11f996a10>, 'Connection to 38.15.153.172 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.140\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd690>, 'Connection to 172.245.166.144 timed out. (connect timeout=5)')))\n",
      "testing 154.201.63.205\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133900e50>, 'Connection to 38.15.155.60 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.194\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339016c0>, 'Connection to 154.201.63.125 timed out. (connect timeout=5)')))\n",
      "testing 154.83.8.155\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f3130>, 'Connection to 38.15.152.14 timed out. (connect timeout=5)')))\n",
      "testing 38.15.153.30\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338223e0>, 'Connection to 38.15.153.107 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.227\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902740>, 'Connection to 154.84.142.117 timed out. (connect timeout=5)')))\n",
      "testing 209.127.39.126\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f3370>, 'Connection to 38.15.154.133 timed out. (connect timeout=5)')))\n",
      "testing 103.247.23.65\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e6d480>, 'Connection to 38.15.154.238 timed out. (connect timeout=5)')))\n",
      "testing 154.202.103.212\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 unknown method')))\n",
      "testing 172.245.166.130\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1338211e0>, 'Connection to 192.210.159.235 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.228\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1334b5900>, 'Connection to 192.210.159.140 timed out. (connect timeout=5)')))\n",
      "testing 154.202.119.218\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f2bf0>, 'Connection to 154.201.63.205 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.160\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339009a0>, 'Connection to 38.15.152.194 timed out. (connect timeout=5)')))\n",
      "testing 154.202.108.157\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133902590>, 'Connection to 154.83.8.155 timed out. (connect timeout=5)')))\n",
      "testing 154.201.61.97\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dead0>, 'Connection to 38.15.153.30 timed out. (connect timeout=5)')))\n",
      "testing 172.245.166.162\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133230a60>, 'Connection to 38.15.154.227 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.65\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f29b0>, 'Connection to 209.127.39.126 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.195\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901630>, 'Connection to 154.202.103.212 timed out. (connect timeout=5)')))\n",
      "testing 209.127.76.120\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339dd930>, 'Connection to 172.245.166.130 timed out. (connect timeout=5)')))\n",
      "testing 209.127.31.224\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1331a4d30>, 'Connection to 38.15.155.228 timed out. (connect timeout=5)')))\n",
      "testing 38.15.152.242\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339de140>, 'Connection to 154.202.119.218 timed out. (connect timeout=5)')))\n",
      "testing 209.127.31.167\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901420>, 'Connection to 192.210.159.160 timed out. (connect timeout=5)')))\n",
      "testing 38.15.155.134\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901390>, 'Connection to 154.202.108.157 timed out. (connect timeout=5)')))\n",
      "testing 192.210.159.126\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f0a30>, 'Connection to 154.201.61.97 timed out. (connect timeout=5)')))\n",
      "testing 38.15.154.84\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f0e20>, 'Connection to 172.245.166.162 timed out. (connect timeout=5)')))\n",
      "testing 104.165.169.63\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13322fcd0>, 'Connection to 192.210.159.65 timed out. (connect timeout=5)')))\n",
      "testing 154.202.124.49\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130e6eb90>, 'Connection to 38.15.152.195 timed out. (connect timeout=5)')))\n",
      "testing 154.83.8.25\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133903940>, 'Connection to 209.127.76.120 timed out. (connect timeout=5)')))\n",
      "testing 51.159.175.71\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339f16c0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 102.68.128.216\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x130f898a0>, 'Connection to 209.127.31.224 timed out. (connect timeout=5)')))\n",
      "testing 154.202.98.161\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1339f2fe0>: Failed to establish a new connection: [Errno 61] Connection refused')))\n",
      "testing 104.164.183.235\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339f38e0>, 'Connection to 38.15.152.242 timed out. (connect timeout=5)')))\n",
      "testing 154.202.105.149\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133823160>, 'Connection to 209.127.31.167 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1331a4c40>, 'Connection to 38.15.155.134 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339de1a0>, 'Connection to 192.210.159.126 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901690>, 'Connection to 38.15.154.84 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1335b8c70>, 'Connection to 104.165.169.63 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133820ca0>, 'Connection to 154.202.124.49 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11fdbb490>, 'Connection to 154.83.8.25 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1339005e0>, 'Connection to 154.202.98.161 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x133901b40>, 'Connection to 104.164.183.235 timed out. (connect timeout=5)')))\n",
      "HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1337639d0>, 'Connection to 154.202.105.149 timed out. (connect timeout=5)')))\n"
     ]
    }
   ],
   "source": [
    "import concurrent.futures\n",
    "\n",
    "proxies = proxies_df[\"IP Address\"].to_list()\n",
    "\n",
    "with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:\n",
    "   test_results = executor.map(test_proxy, proxies)\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "\n",
    "url = url_builder(job_title='python developer', location='Fort Worth,TX')\n",
    "\n",
    "driver = webdriver.Chrome()\n",
    "print (url)\n",
    "driver.get(url)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
